FROM hoosin/alpine-nginx-nodejs:latest AS build-stage
COPY . /app
WORKDIR /app
RUN npm install
RUN npm run build

FROM hoosin/alpine-nginx-nodejs
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/configfile.template
COPY --from=build-stage /app/build /usr/share/nginx/html
ENV PORT 80
ENV HOST 0.0.0.0
ENV API_HOST http://192.168.99.100:5000
RUN sh -c "envsubst '\$PORT \$API_HOST'  < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf"

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]