export const NEXT_QUESTION = 'NEXT_QUESTION';
export const FETCH_SYMPTOMS_RECORDS = 'FETCH_SYMPTOMS_RECORDS';
export const SYMPTOMS_RECORDS_LOADED = 'SYMPTOMS_RECORDS_LOADED';
export const API_ERROR = 'API_ERROR_RAISED';
